spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservice
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: vivek9087

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: Hotel-Service
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:9090/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8083

